
  #kubectl patch storageclass openebs-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  hostpathClass:
    name: openebs-hostpath
    enabled: true
    reclaimPolicy: Delete
    isDefaultClass: true