ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: my-issuer
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-namespace: default
  hosts:
    - host: pg.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: pgadmin-tls
     hosts:
       - pg.example.com
persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi
env:
  email: pgadmin@example.com
  password: SomePasswordHere
